"""
Phase 1 Configuration Settings
Load all configuration from environment variables
"""

from pydantic_settings import BaseSettings
from typing import List
from pathlib import Path


class Settings(BaseSettings):
    """Application settings loaded from environment variables."""
    
    # Telegram Bot Configuration
    telegram_bot_token: str = ""
    telegram_api_id: str = ""
    telegram_api_hash: str = ""
    telegram_session_string: str = ""  # Generated by generate_session.py
    
    # MongoDB Configuration
    mongo_uri: str = ""
    mongo_db_name: str = "escrow_phase1"
    
    # Admin Configuration
    admin_user_ids: List[int] = []
    
    # Escrow Addresses (YOUR ADDRESSES)
    escrow_btc_address: str = ""
    escrow_usdt_address: str = ""
    escrow_eth_address: str = ""
    escrow_ltc_address: str = ""
    
    # Server Configuration
    render_api_url: str = "http://localhost:8000"
    webhook_url: str = "http://localhost:8000/webhook"
    
    # Server
    port: int = 8000
    secret_key: str = ""

    # Logging
    log_level: str = "INFO"
    log_file: str = "logs/escrow_bot.log"
    heartbeat_interval_seconds: int = 300
    
    # App Settings
    max_deal_amount: float = 100000
    deal_expiry_hours: int = 24
    
    # Currency Configuration
    supported_currencies: List[str] = ["BTC", "USDT", "ETH", "LTC"]
    
    class Config:
        env_file = ".env"
        env_file_encoding = "utf-8"
        case_sensitive = False
        extra = "ignore"
    
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        
        # Parse admin user IDs from comma-separated string if needed
        if isinstance(self.admin_user_ids, str):
            self.admin_user_ids = [
                int(uid.strip()) for uid in self.admin_user_ids.split(",")
                if uid.strip().isdigit()
            ]


# Global settings instance
settings = Settings()


def get_project_root() -> Path:
    """Get the project root directory."""
    return Path(__file__).parent.parent


def ensure_log_directory():
    """Ensure logs directory exists."""
    log_dir = Path(get_project_root()) / "logs"
    log_dir.mkdir(exist_ok=True)
