"""
Phase 1 Configuration Settings
Load all configuration from environment variables
"""

from pydantic_settings import BaseSettings, SettingsConfigDict
from pydantic import field_validator
from typing import Any
from pathlib import Path
import json


class Settings(BaseSettings):
    """Application settings loaded from environment variables."""
    
    # Telegram Bot Configuration
    telegram_bot_token: str = ""
    telegram_api_id: str = ""
    telegram_api_hash: str = ""
    telegram_session_string: str = ""  # Generated by generate_session.py
    
    # MongoDB Configuration
    mongo_uri: str = ""
    mongo_db_name: str = "escrow_phase1"
    
    # Admin Configuration
    admin_user_ids: Any = []
    
    # Escrow Addresses (YOUR ADDRESSES)
    escrow_btc_address: str = ""
    escrow_usdt_address: str = ""
    escrow_eth_address: str = ""
    escrow_ltc_address: str = ""
    
    # Server Configuration
    render_api_url: str = "http://localhost:8000"
    webhook_url: str = "http://localhost:8000/webhook"
    
    # Server
    port: int = 8000
    secret_key: str = ""

    # Logging
    log_level: str = "INFO"
    log_file: str = "logs/escrow_bot.log"
    heartbeat_interval_seconds: int = 300
    
    # App Settings
    max_deal_amount: float = 100000
    deal_expiry_hours: int = 24
    
    # Currency Configuration
    supported_currencies: Any = ["BTC", "USDT", "ETH", "LTC"]
    
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    @field_validator("admin_user_ids", mode="before")
    @classmethod
    def parse_admin_user_ids(cls, value):
        """Allow ADMIN_USER_IDS as JSON list or comma-separated values."""
        if value is None or value == "":
            return []

        if isinstance(value, list):
            return [int(v) for v in value]

        if isinstance(value, str):
            raw = value.strip()

            if not raw:
                return []

            if raw.startswith("[") and raw.endswith("]"):
                parsed = json.loads(raw)
                return [int(v) for v in parsed]

            return [
                int(uid.strip())
                for uid in raw.split(",")
                if uid.strip().isdigit()
            ]

        return value

    @field_validator("supported_currencies", mode="before")
    @classmethod
    def parse_supported_currencies(cls, value):
        """Allow SUPPORTED_CURRENCIES as JSON list or comma-separated values."""
        if value is None or value == "":
            return ["BTC", "USDT", "ETH", "LTC"]

        if isinstance(value, list):
            return [str(v).strip().upper() for v in value if str(v).strip()]

        if isinstance(value, str):
            raw = value.strip()

            if not raw:
                return ["BTC", "USDT", "ETH", "LTC"]

            if raw.startswith("[") and raw.endswith("]"):
                parsed = json.loads(raw)
                return [str(v).strip().upper() for v in parsed if str(v).strip()]

            return [cur.strip().upper() for cur in raw.split(",") if cur.strip()]

        return value
    
    def __init__(self, **kwargs):
        super().__init__(**kwargs)


# Global settings instance
settings = Settings()


def get_project_root() -> Path:
    """Get the project root directory."""
    return Path(__file__).parent.parent


def ensure_log_directory():
    """Ensure logs directory exists."""
    log_dir = Path(get_project_root()) / "logs"
    log_dir.mkdir(exist_ok=True)
